### PR TITLE
Switch building system from IntelliJ to Gradle

### LINKED ISSUE #44: Maven support
**Is your feature request related to a problem? Please describe.**
I would like to easily kick-off new project with standart tools like Maven or Gradle, with a propper dependency management. It also will allow smooth compiling of the final game on CI for different platforms. 

**Describe the solution you'd like**
I see that it can be ticky part, cause the project itserlf doesn't use propper build management tool. So, I would start with modularity and moving this porject itself to Maven or Gradle.

**Describe alternatives you've considered**
Alternatively, just publish to maven existing build outputs for different platfroms, i.t. Linux, MacOS, Windows.

**Additional context**
-

### PR DESCRIPTION
**Pull request by Irgendwer01**
## What
This PR changes the building system from IntelliJ to Gradle, allowing for easier dependency management and distribution. 
It also changes dependencies whether possible to download from the maven central repository instead of having it on the github repository to avoid future license conflicts.
The biggest change is that libraries **are not embed anymore into Raylib itself**, this should avoid future license conflicts as well but I can revert that if needed. I'm also not sure whether an inclusion of libraries will prevent a publication on maven Central.

Closes #44

### CODE REVIEW

**Comment by CreedVI** [comment]
Awesome work! Thanks for taking care of that.

**Comment by Irgendwer01** [comment]
@CreedVI Is there an Discord or something in that direction where it's possible to talk about Raylib-J?

**Comment by CreedVI** [comment]
@Irgendwer01 you can always find me in the #Raylib-JVM channel of the Taylor discord https://discord.com/invite/raylib

**Comment by ejenk0** [comment]
Hi! I am trying to contribute to the project but I am not able to figure out how to build it properly with Gradle. Could you provide some basic instructions? I am using IntelliJ IDEA and have all of these options, but no matter what I do I can't seem to run a hello world when compiling from source.

Screenshot 2024-05-15 at 2 16 09 pm

I have tried sticking a main function in the Raylib.java file, I have tried compiling to .jar and including it in a seperate project, nothing seems to work. I have never used Gradle before so please excuse my noobishness! :)

@Irgendwer01 @CreedVI

**Comment by CreedVI** [comment]
@ejenk0 

You use the "build" task under the build folder in your gradle tasks to build the .jar

From there you have to include the .jar you compiled in your new project. What are the errors you're receiving from the fresh project? Feel free to reach out in the Raylib discord if you need help

**Pull request merged**
